<?php
$vAllowOperate = count($operators);
?>
<div class="board-content-header">
    <ul class="list-unstyled ul-list clearfix<?=$vAllowOperate ? '' : ' ul-list-noop'?>">
        <li><?=H(T('创建时间'))?></li>
        <li><?=H(T('订单编号'))?></li>
        <li><?=H(T('商品'))?></li>
        <li><?=H(T('买方'))?></li>
        <li><?=H(T('供应商'))?></li>
        <li><?=H(T('金额'))?></li>
        <li><?=H(T('状态'))?></li>
        <?php if ($vAllowOperate) {?>
        <li>&#160;</li>
        <?php }?>
    </ul>
</div>
<div class="board-content-body">
    <?php
    if (count($requests)) foreach ($requests as $vRequest) {?>
        <ul class="list-unstyled ul-list clearfix row<?=$vAllowOperate ? '' : ' ul-list-noop'?>">
            <li style="font-size:11px;line-height:3.2em"><?=H($vRequest->order->ctime)?></li>
            <li><a href="order-info/<?=H($vRequest->id)?>"><?=H($vRequest->order->voucher)?></a></li>
            <li>
            <?php 
            $vItems = (array)$vRequest->order->items;
            $tmpI = 1;
            foreach ((array)$vItems as $vPID=>$vPData) {?>
                <?php if ($tmpI++>3) { ?>
                <div>...</div>
                <?php } else { ?>
                <div title="<?=H($vPData['name'])?>"><?=H($vPData['name'])?></div>
                <?php }?>
            <?php }?>
            </li>
            <li title="<?=H($vRequest->order->group->title)?>"><?=H($vRequest->order->group->title)?></li>
            <li title="<?=H($vRequest->order->vendor->name)?>"><?=H($vRequest->order->vendor->name)?></li>
            <li><?=H(money_format('%.2n', $vRequest->order->price))?></li>
            <li><?=H(\Gini\ORM\Request::$status_titles[$vRequest->status])?></li>
            <?php if ($vAllowOperate) {?>
            <li>
                <?php foreach ($operators as $vKey=>$vOp) {?>
                <span class="app-op-per-handler btn btn-link" data-id="<?=H($vRequest->id)?>" data-key="<?=H($vKey)?>"><?=H($vOp['title'])?></span>
                <?php }?>
            </li>
            <?php }?>
        </ul>
    <?php }?>
</div>

