<?php
$me = _G('ME');
?>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid gini-layout-width">
        <div class="navbar-header">
            <ul class="nav navbar-nav">
                <li class="site-title">
                    <a href="gapper/client/gohome">
                        <?= H(T(\Gini\Config::get('app.title')))?>
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="position:relative">
                <?php if($me->id) {?>
                        <li role="presentation">
                            <a href="logout" tabindex="-1" role="menuitem"><?= H(T('登出系统'))?></a>
                        </li>
                <?php } else { ?>
                    <li role="presentation">
                        <a href="login" tabindex="-1" role="menuitem"><?= H(T('登录'))?></a>
                    </li>
                <?php }?>
            </ul>
        </div>
    </div>
</nav>

