<?php
$checkActive = function($routeCheckings, $exceptCheckings=[]) use($route) {
    foreach ($exceptCheckings as $exceptChecking) {
        if (0 == strncmp($exceptChecking, $route, strlen($exceptChecking))) {
            return;
        }
    }
    foreach ($routeCheckings as $routeChecking) {
        if (0 == strncmp($routeChecking, $route, strlen($routeChecking))) {
            return ' class="active"';
        }
    }
};
$me = _G('ME');
$group = _G('GROUP');
?>

<div class="sidebar-menu">
    <div class="menu-item">
        <a href="order" <?= $checkActive(['order'], ['order/done', 'order-info'])?>>
            <i class="fa fa-fw fa-list"></i>
            <span><?= H(T('待审采购')) ?></span>
        </a>
    </div>
    <div class="menu-item">
        <a href="order/done" <?= $checkActive(['order/done'], ['order/info'])?>>
            <i class="fa fa-fw fa-list"></i>
            <span><?= H(T('审核历史')) ?></span>
        </a>
    </div>
    <?php foreach ((array)$apps as $app_id => $app) {?>
    <div class="menu-item">
        <a href="gapper/client/go/<?=H($app_id)?>/<?=$group->id?>"><i class="fa fa-fw fa-<?= H($app['font_icon']?:'cubes') ?>"></i> &nbsp;<?= H($app['short_title'] ?: $app['title']) ?></a>
    </div>
    <?php }?>
</div>
