<?php
$checkActive = function($routeCheckings, $exceptCheckings=[]) use($route) {
    if (in_array($route, $exceptCheckings)) return;
    foreach ($routeCheckings as $routeChecking) {
        if (0 == strncmp($routeChecking, $route, strlen($routeChecking))) {
            return ' class="active"';
        }
    }
};
$me = _G('ME');
$group = _G('GROUP');
?>

<div class="sidebar-menu">
    <div class="menu-item">
        <a href="order" <?= $checkActive(['order'])?>>
            <i class="fa fa-fw fa-bar-chart"></i>
            <span><?= H(T('订单管理')) ?></span>
        </a>
    </div>
</div>
