<div class="board-header clearfix" data-require="page/order">
    <div class="board-header-form pull-right text-nowrap" style="margin-top:13px;">
        <input type="text" name="q" class="form-control" style="display:inline-block;width:240px;" placeholder="<?=H(T('输入订单编号或者商品名称搜索'))?>" />
        <button class="btn btn-default"><i class="fa fa-fw fa-search"></i></button>
    </div>
</div>
<div class="board-content">
    <div class="board-content-order-title board-content-against-right clearfix">
        <div class="pull-left block-order-body" style="width:80%;"><ul class="list-unstyled ul-order-list">
            <li><?=H(T('创建时间'))?></li>
            <li><?=H(T('订单编号'))?></li>
            <li><?=H(T('商品'))?></li>
            <li><?=H(T('买方'))?></li>
            <li><?=H(T('供应商'))?></li>
            <li><?=H(T('金额'))?></li>
            <li><?=H(T('状态'))?></li>
        </ul></div>
        <div class="pull-left" style="width:20%;">&#160;</div>
    </div>
</div>
