<div class="board-header clearfix" data-require="page/order">
    <div class="board-header-form pull-right text-nowrap" style="margin-top:13px;"><form action="ajax/request/more/0/<?=H($type)?>">
        <button class="btn btn-default app-q-search-handler pull-right"><i class="fa fa-fw fa-search"></i></button>
        <input type="text" name="q" class="form-control" style="display:inline-block;width:240px;margin-right:10px;" placeholder="<?=H(T('输入订单编号或者商品名称搜索'))?>" />
    </form></div>
</div>
<div class="board-content">
    <?=$list?>
</div>
