<div class="board-header clearfix" data-require="page/order">
    <div class="board-header-form pull-right text-nowrap" style="margin-top:13px;">
        <input type="text" name="q" class="form-control" style="display:inline-block;width:240px;" placeholder="<?=H(T('输入订单编号或者商品名称搜索'))?>" />
        <button class="btn btn-default"><i class="fa fa-fw fa-search"></i></button>
    </div>
</div>
<div class="board-content">
    <div class="board-content-header">
        <ul class="list-unstyled ul-list clearfix">
            <li><?=H(T('创建时间'))?></li>
            <li><?=H(T('订单编号'))?></li>
            <li><?=H(T('商品'))?></li>
            <li><?=H(T('买方'))?></li>
            <li><?=H(T('供应商'))?></li>
            <li><?=H(T('金额'))?></li>
            <li><?=H(T('状态'))?></li>
            <li>&#160;</li>
        </ul>
    </div>
    <div class="board-content-body">
        <ul class="list-unstyled ul-list clearfix">
        </ul>
    </div>
</div>
